#!/bin/bash
rm **.{out,aux,log,blg,brf,gz,snm,nav,toc,blg}  
find . -name *.pyc | xargs rm 
find . -name __pycache__ | xargs rm -rf
find . -name *checkpoint.py | xargs rm
find . -name .ipynb_checkpoints | xargs rm -rf
