#!/bin/bash

for ext in snm nav log brf gz toc blg out aux; do
    find . -name "*.$ext" -delete
done

find . -name __pycache__ -exec rm -rf {} +
find . -name *checkpoint.py -exec rm -rf {} +
find . -name .ipynb_checkpoints -exec rm -rf {} +