#!/bin/bash
#Use this to check the progress of dd clone in terminal
# while [[ true ]]; do
# 	sudo sh -c 'cat /dev/sda > /dev/sdb'& pid=$!;
#
# 	sudo kill -USR1 $pid; sleep 1; #kill $pid
# 	sleep 10;
# 	date
#
# 	printf '\n\n'
# done


while [[ true ]]; do
	sudo sh -c 'cat /dev/sda > /dev/sdb'& pid=$!;
	cat /proc/$pid/fdinfo/0
	date

	printf '\n\n'
	sleep 2
done
