#!/bin/bash

# commits a change and pushes a change
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1/'
}

commit_gps() {

  echo -e "entering gps directory"

  cd /home/$USER/catkin_ws/src/gps;

  git add --all;

  printf "\nHello "$USER". Please enter the commit message: "

  read msg

  git commit -m "$msg"

  printf "\nPlease enter the name of the upstream remote\n\nOr type Enter to push to current branch that you are on\n\n "

  read remote

  if [ remote == "" ]; then
     remote=parse_git_branch
  fi

  git push -u origin $remote

  printf "\n\n"
}


commit_schol() {
  echo -e "entering scholternships directory"

  cd /home/$USER/Desktop/scholternships

  git add --all;

  printf "\nHello "$USER". Please enter the commit message: "

  read msg

  git commit -m "$msg"

  printf "\nPlease enter the name of the upstream remote\n\nOr type Enter to push to current branch that you are on\n\n "

  read remote

  if [ remote == "" ]; then
     remote=parse_git_branch
  fi

  git push -u origin $remote

  printf "\n\n"
}


commit_papers() {
  echo -e "entering Papers directory"

  cd /home/$USER/Documents/Papers

  git add --all;

  printf "\nHello "$USER". Please enter the commit message: "

  read msg

  git commit -m "$msg"

  printf "\nPlease enter the name of the upstream remote\n\nOr type Enter to push to current branch that you are on\n\n "

  read remote

  if [ remote == "" ]; then
     remote=parse_git_branch
  fi

  git push -u origin $remote

  printf "\n\n"
}


commit_blog(){

  echo -e "entering blog directory"

  cd /home/$USER/Documents/scholternships

  git add --all;

  printf "\nHello "$USER". Please enter the commit message: "

  read msg

  git commit -m "$msg"

  printf "\nPlease enter the name of the upstream remote\n\nOr type Enter to push to current branch that you are on\n\n "

  read remote

  if [ remote == "" ]; then
     remote=parse_git_branch
  fi

  git push -u origin $remote

  printf "\n\n"
}


commit_gps

commit_schol

commit_papers

commit_blog
