#!/bin/bash

printf "\nHello "$USER". Please enter the commit message: "

read msg

# commits a change and pushes a change
git add --all;

git commit -m "$msg"

parse_git_branch() {
git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1/'
}

printf "\nPlease enter the name of the upstream remote\n\nOr type Enter to push to current branch that you are on\n\n "

read remote

if [ remote == "" ]; then
   remote=parse_git_branch
fi

echo -e "pushing from all local origins?[y|n]\n"
read num_origins

if [ num_origins == "y" ]; then
  for orig in $(git remote); 
	do echo "pushing from $orig to $remote\n" &&
	    git push -u $orig $remote; 
   done
elif [ num_origins == "n" ]; then
  git push -u origin $remote
fi

printf "\n\n"
