#!/bin/bash
pdfjoin wafr.pdf iros18.pdf iROS2017.pdf CASE2016.pdf CASE2015.pdf Yara.pdf

wait

if [ -d Papers_Unabridged.pdf ]; then
    rm Papers_Unabridged.pdf
fi


mv Yara-joined.pdf Papers_Unabridged.pdf
