#! /bin/bash
# this scripts backs up all git repos on my locals
POSITIONAL=()
while [[ $# -gt 0 ]]
do key="$1"

case $key in
  -b|--blog) #  check if blog has unstaged commits
  blogmit="$2"
  shift # past argument
  shift # past value
  ;;
  -p|--papers) #  check if papers has unstaged commits
  papersmit="$2"
  shift # past argument
  shift # past value
  ;;
  -n|--niw)  # NIW?
  niwmit="$2"
  shift # past arg
  shift # past value
  ;;
  -s|--sup)  # superchicko?
  supmit="$2"
  shift # past arg
  shift # past value
  ;;
  -e|--sweng)  # superchicko?
  supmit="$2"
  shift # past arg
  shift # past value
  ;;
  *) # unknown option
  POSITIONAL+=("$1") # save in array for later use
  shift # past arg
  ;;
esac
done
set -- "${POSITION[@]}" # restore positional parameters

parse_git_branch() {
git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1/'
}

if [[ -z "$blogmit" ]]; then
  echo -e "usage: `basename $0` [-b|--blog] [-p|--papers]  [-n|--niw] [-s|--sup]\t
       e.g. `basename $0` -b y -p y -n y -s y \n\t
                            -b push/pull blog directory  [y/n] \t
                            -p push/pull papers directory  [y/n] \t
                            -n push/pull niw directory  [y/n] \t
                            -s push/pull superchicko directory [y/n] \t 
                            -e push/pull swengr directory [y/n]"
  exit 1
fi

# source aliases
shopt -s expand_aliases
source ~/.zsh_aliases

is_yes() {
        yesses={y,Y,yes,Yes,YES}
        if [[ $yesses =~ $1 ]]; then
                echo 1
        fi
        }

is_no() {
        noses={n,N,no,No,No}
        if [[ $noses =~ $1 ]]; then
                echo 1
        fi
        }

pull_and_push(){
   echo -e "\n>>>>>>>>>>>>>>>>>>==============================="
   echo -e "Git in $1"
   echo -e ">>>>>>>>>>>>>>>>>>===============================\n"
   cd $2  # cd to given directory
   git add -A; git commit -m "auto commit from gitci";
   git pull origin $parse_git_branch; git push origin $parse_git_branch
}        

# if [[ $(is_yes $blog) ]]; then
#    echo -e "\n>>>>>>>>>>>>>>>>>>==============================="
#    echo -e "Git in blog"
#    echo -e ">>>>>>>>>>>>>>>>>>===============================\n"
#    blog  # assumes blog as alias
#    git add -A; git commit -m "auto commit";
#    git pull origin master; git push origin master
# fi

# if [[ $(is_yes $papers) ]]; then
#    echo -e "\n>>>>>>>>>>>>>>>>>>==============================="
#    echo -e "Git in papers"
#    echo -e ">>>>>>>>>>>>>>>>>>===============================\n"
#    # cd ~/Documents/Papers  # assumes papers as an alias
#    papers
#    git add -A; git commit -m "auto commit";
#    git pull origin master; git push origin master
# fi

# if [[ $(is_yes $niw) ]]; then
#    echo -e "\n>>>>>>>>>>>>>>>>>>==============================="
#    echo -e "Git in NIW"
#    echo -e ">>>>>>>>>>>>>>>>>>===============================\n"
#    # cd ~/Desktop/Personals  # assumes papers as an alias
#    niw
#    git add -A; git commit -m "auto commit";
#    git pull origin master; git push origin master
# fi

# if [[ $(is_yes $sup) ]]; then
#    echo -e "\n>>>>>>>>>>>>>>>>>>==============================="
#    echo -e "Git in Superchicko"
#    echo -e ">>>>>>>>>>>>>>>>>>===============================\n"
#    # cd ~/catkin_ws/src/superchicko  # assumes papers as an alias
#    sup
#    git add -A; git commit -m "auto commit";
#    git pull origin $parse_git_branch; git push origin $parse_git_branch
# fi

# if [[ $(is_yes $sweng) ]]; then
#    echo -e "\n>>>>>>>>>>>>>>>>>>==============================="
#    echo -e "Git in sweng"
#    echo -e ">>>>>>>>>>>>>>>>>>===============================\n"
#    # cd ~/catkin_ws/src/superchicko  # assumes papers as an alias
#    cd ~/Documents/FB19
#    git add -A; git commit -m "auto commit";
#    git pull origin $parse_git_branch; git push origin $parse_git_branch
# fi

if [[ $(is_yes $blog) ]]; then
   pull_and_push "blog" "~/Documents/blog"
fi

if [[ $(is_yes $papers) ]]; then
   pull_and_push "papers"  "~/Documents/papers"
fi

if [[ $(is_yes $NIW) ]]; then
   pull_and_push "NIW"  "~/Desktop/Personals"
fi

if [[ $(is_yes $sup) ]]; then
  if [[ uname == "Darwin" ]]; then  
    pull_and_push "superchicko" "~/ros_ws/src/superchicko"
  elif [[ uname == "Linux" ]]; then
    pull_and_push "superchicko" "~/catkin_ws/src/superchicko"
  fi
fi

if [[ $(is_yes $sweng) ]]; then
   pull_and_push "SWEng"  "~/Documents/FB19"
fi


echo -e "\n>>>>>>>>>>>>>>>>>>==============================="
echo -e "We are done now"
echo -e ">>>>>>>>>>>>>>>>>>===============================\n"