#! /bin/bash
# this scripts backs up all git repos on my locals
POSITIONAL=()
while [[ $# -gt 0 ]]
do key="$1"

case $key in
  -b|--blog) #  check if blog has unstaged commits
  blogmit="$2"
  shift # past argument
  shift # past value
  ;;
  -p|--papers) #  check if papers has unstaged commits
  papersmit="$2"
  shift # past argument
  shift # past value
  ;;
  -n|--niw)  # NIW?
  niwmit="$2"
  shift # past arg
  shift # past value
  ;;
  -s|--sup)  # superchicko?
  supmit="$2"
  shift # past arg
  shift # past value
  ;;
  -e|--sweng)  # superchicko?
  supmit="$2"
  shift # past arg
  shift # past value
  ;;
  -w|--screws)  # superchicko?
  screw="$2"
  shift # past arg
  shift # past value
  ;;
  *) # unknown option
  POSITIONAL+=("$1") # save in array for later use
  shift # past arg
  ;;
esac
done
set -- "${POSITION[@]}" # restore positional parameters

parse_git_branch() {
git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1/'
}

if [[ -z "$blogmit" ]]; then
  echo -e "usage: `basename $0` [-b|--blog] [-p|--papers]  [-n|--niw] [-s|--sup] [-w|--screws]\t
       e.g. `basename $0` -b y -p y -n y -s y -w y \n\t
                            -b push/pull blog directory  [y/n] \t
                            -p push/pull papers directory  [y/n] \t
                            -n push/pull niw directory  [y/n] \t
                            -s push/pull superchicko directory [y/n] \t 
                            -e push/pull swengr directory [y/n]\t
                            -w push/pull screws directory [y/n]"
  exit 1
fi

is_yes() {
        yesses={y,Y,yes,Yes,YES}
        if [[ $yesses =~ $1 ]]; then
                echo 1
        fi
        }

is_no() {
        noses={n,N,no,No,No}
        if [[ $noses =~ $1 ]]; then
                echo 1
        fi
        }

pull_and_push(){
   echo -e "\n>>>>>>>>>>>>>>>>>>==============================="
   echo -e "Git in $1"
   echo -e ">>>>>>>>>>>>>>>>>>===============================\n"
   git add -A; git commit -m "auto commit from gitci";
   git pull origin $parse_git_branch; git push origin $parse_git_branch
}        

# source aliases
shopt -s expand_aliases
source ~/.zsh_aliases

if [[ $(is_yes $blog) ]]; then
   blog
   # update all papers
   cp ../Papers/SRS/Continuum/kinecontrol/kinecontrol.pdf downloads/Papers/kinecontrol.pdf
   cp ../Papers/SRS/Continuum/model/model.pdf downloads/Papers/ContinuumI.pdf
   cp ../Papers/SRS/Springer2019/springer19.pdf downloads/Papers/Springer19.pdf

   pull_and_push "blog" 
fi

if [[ $(is_yes $papers) ]]; then
   papers
   pull_and_push "papers" 
fi

if [[ $(is_yes $NIW) ]]; then
    niw
    pull_and_push "NIW" 
fi

if [[ $(is_yes $sup) ]]; then
  sup
  pull_and_push "superchicko" 
fi

if [[ $(is_yes $sweng) ]]; then
  cd "~/Documents/FB19"
  pull_and_push "SWEng"  
fi

if [[ $(is_yes $screw) ]]; then
  cd "~/Documents/screws"
  pull_and_push "screws"  
fi


echo -e "\n>>>>>>>>>>>>>>>>>>==============================="
echo -e "We are done now"
echo -e ">>>>>>>>>>>>>>>>>>===============================\n"