#! /bin/bash
#git config myne
git config --global user.name YOUR_GIT_USERNAME
git config --global user.email your@email.com
git config --global core.editor vim
git config --list			# will display the above info in terminal

printf '\n\n Cache the password\n\n'
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=3600'
