#!/bin/bash

wget http://downloads.sourceforge.net/project/glfw/glfw/3.0.1/glfw-3.0.1.zip
unzip glfw-3.0.1.zip
cd glfw-3.0.1/
mkdir build
cd build
export MACOSX_DEPLOYMENT_TARGET=10.8 
cmake -D GLFW_NATIVE_API=1 -D CMAKE_OSX_ARCHITECTURES="i386;x86_64" -D BUILD_SHARED_LIBS=ON -D CMAKE_C_COMPILER=clang ../
make

echo $(ls -l src/libglfw*)
