#! /bin/bash

printf "\nHello "$USER". To start your ssh tunnel,
		\nplease enter the machinename, e.g\n\"rok80\", \"swmed\", \"lexBerry\", \"rootBerry\" or , \"piBerry\" , \"cbica\" \n\n"

# # \ne.g. as lekan@rok80x8.dhcp.swmed.org
# \n(if logging on to rok80, just hit the [RETURN] key):

hosts=("lekan@rok80x8.dhcp.swmed.org" "lex@129.112.133.210" "root@205.208.91.240" "pi@205.208.91.240" "lex@205.208.91.240"  "ogunmolo@cbica-cluster.uphs.upenn.edu")
read computer

is_rok80(){
	rok80s={rok80,ROK80,Rok80,rOK80}
	if [[ $rok80s =~ $1 ]]; then
		echo 1
	fi
}

is_cbica(){
	cbica={cbica,CBICA,cbc}
	if [[ $cbica =~ $1 ]]; then
		echo 1
	fi
}

is_swmed(){
	swmed={swmed,utsw,SWMED,UTSW,bl11,BL11}
	if [[ $swmed =~ $1 ]]; then
		echo 1
	fi
}

is_piberry(){
	piberry={pi,piBerry,PiBerry}
	if [[ $piberry =~ $1 ]]; then
		echo 1
	fi
}

is_lexberry(){
	lexberry={lex,lexBerry,lexberry}
	if [[ $lexberry =~ $1 ]]; then
		echo 1
	fi
}

is_rootberry(){
	rootberry={rootBerry,rootBerry}
	if [[ $rootberry =~ $1 ]]; then
		echo 1
	fi
}

if [[ $(is_rok80 $computer) ]]; then
    remotecomp=${hosts[0]}
elif [[ $(is_swmed $computer) ]]; then
    remotecomp=${hosts[1]}
elif [[ $(is_rootberry $computer) ]]; then
    remotecomp=${hosts[2]}
elif [[ $(is_piberry $computer) ]]; then
    remotecomp=${hosts[3]}
elif [[ $(is_lexberry $computer) ]]; then
    remotecomp=${hosts[4]}
elif [[ $(is_cbica $computer) ]]; then
    remotecomp=${hosts[5]}
else
	echo -e "\n\nYou have selected an invalid remote computer\n
			Only swmed, rok80, cbica and berry accounts are valid for now"
	exit 0
fi

echo -e "\n\nyou have chosen $remotecomp\n\n"

printf "\nPlease enter the port to use for ssh port forwarding [a four digit number]\n(if you would like to use "6140", just hit the [RETURN] key): "
read port

if [ port == "" ]; then
    port="6140"
fi

printf "\n\nbinding localhost:$port to "$remotecomp"\n\n"
ssh -N -f -L localhost:$port:localhost:$port $remotecomp

echo -e "Done. \nYou may now type localhost:$port/lab? in your favorite browser. \n\nThanks!\n"
